### ISSUE TITLE
How to get torrent infohashes?

### ISSUE THREAD

**Issue by dessalines** [fanpei91/simDHT#11]
I see that the output is logging the peer `info_hash`es, but how do I print out the bencodes for that peers torrents? IE, how do I make a request to get that peer's torrents?

**Comment by fanpei91** [comment]
see my [p2pspider](https://github.com/fanpei91/p2pspider)

**Comment by dessalines** [comment]
Not sure if this is the best way to contact you, but I've been messing with p2pspider and it works really great, but you can't open up issues on there. I'm wondering (since its running a DHT client), if it can get seeder/peer counts? I could make a torrent client that fetches these, but it seems redundant.

**Comment by fanpei91** [comment]
Sorry, I can't understand what are you saying.

**Comment by dessalines** [comment]
can p2pspider get seeder / peer counts?

**Comment by fanpei91** [comment]
You can implements the feature. you can save infohash into database and count the number of a infohash occurrences. Just write code into `index.js`.

**Comment by fanpei91** [comment]
```
p2p.ignore(function (infohash, rinfo, callback) {
    var torrentFilePathSaveTo = path.join(__dirname, "torrents", infohash + ".torrent");
    fs.exists(torrentFilePathSaveTo, function(exists) {
        callback(exists); //if is not exists, download the metadata.
    });
});
```

The `rinfo` is the peer/seeder address.

**Comment by dessalines** [comment]
Also, is there any way to get seeder counts? I'm looking at `btclient.js`, but I can't find seeders.
